project:
  type: website
  output-dir: docs/
  execute-dir: project
  render:
    - "*.qmd"
    - "!xiang2023-extension/*.qmd"
  resources:
    - "webppl vs memo/*-comic.png"

format:
  html:
    toc: true
    toc-expand: true