[workspace]
authors = ["jczimm <jczimm@jczimm.com>"]
channels = ["conda-forge"]
name = "memo-sandbox"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
preview = "quarto preview"
render = "quarto render"
rerender = "quarto render --cache-refresh"
force_rerender = "rm -rf .quarto && quarto render"

[pypi-dependencies]
memo-lang = ">=1.2.7, <2"
jax = { version = ">=0.4.21, <0.9", extras = ["cuda12"] }

[dependencies]
python = ">=3.14.0,<3.15"
pip = ">=25.2,<26"
ipykernel = ">=6.30.1,<7"
matplotlib = ">=3.10.6,<4"
graphviz = ">=13.1.2,<14"
r = ">=4.5,<4.6"
r-devtools = ">=2.4.6,<3"
r-tidyverse = ">=2.0.0,<3"
r-reticulate = ">=1.43.0,<2"
r-quarto = ">=1.5.1,<2"
jupyterlab = ">=4.4.9,<5"
r-httpgd = ">=2.0.4,<3"
r-languageserver = ">=0.3.16,<0.4"
jupyter-cache = ">=1.0.1,<2"
pandas = ">=2.3.3,<3"
